create table variables
(
    id                             bigint generated by default as identity
        primary key,
    string_id                      varchar(200)  default NULL::character varying,
    slug                           varchar(200)  default NULL::character varying,
    name                           varchar(125)                            not null,
    abbreviated_name               varchar(100)  default NULL::character varying,
    additional_meta_data           text,
    canonical_variable_id          integer,
    created_at                     timestamp     default CURRENT_TIMESTAMP not null,
    creator_user_id                uuid
        references users,
    default_unit_id                varchar(125)                            not null,
    default_value                  double precision,
    deleted_at                     timestamp,
    deletion_reason                varchar(280)  default NULL::character varying,
    description                    text,
    ranges                         jsonb,
    reference_urls                 varchar(2083) default NULL::character varying,
    parent_id                      integer,
    ref_aact_id                    integer,
    ref_fdc_id                     integer,
    ref_gene_ontology_id           integer,
    ref_hmdb_id                    integer,
    ref_icd10_id                   integer,
    ref_loinc_id                   varchar,
    ref_meddra_all_indications_id  integer,
    ref_meddra_all_side_effects_id integer,
    ref_rxnorm_id                  integer,
    ref_snomed_id                  integer,
    ref_uniprot_id                 integer,
    synonyms                       varchar(600)  default NULL::character varying,
    updated_at                     timestamp     default CURRENT_TIMESTAMP not null,
    tags                           varchar(600)  default NULL::character varying,
    variable_category_id           integer,
    version_first_released         varchar(255)  default NULL::character varying,
    version_last_changed           varchar(255)  default NULL::character varying,
    constraint variables_string_id_slug_abbreviated_name_name_canonical_va_key
        unique (string_id, slug, abbreviated_name, name, canonical_variable_id)
);

comment on table variables is 'Variables with their metadata for reference in measurement data points';

alter table variables
    owner to supabase_admin;

create policy "Allow logged-in read access" on variables
    as permissive
    for select
    using (auth.role() = 'authenticated'::text);

create policy "Allow individual insert access" on variables
    as permissive
    for insert
    with check (auth.uid() = creator_user_id);

create policy "Allow individual delete access" on variables
    as permissive
    for delete
    using (auth.uid() = creator_user_id);

create policy "Allow authorized delete access" on variables
    as permissive
    for delete
    using authorize('variables.delete'::app_permission, auth.uid());

create policy "Allow read access for all users" on variables
    as permissive
    for select
    using true;

create policy "Allow write access for all users TEMP" on variables
    as permissive
    for insert
    with check true;

grant delete, insert, references, select, trigger, truncate, update on variables to postgres;

grant delete, insert, references, select, trigger, truncate, update on variables to anon;

grant delete, insert, references, select, trigger, truncate, update on variables to authenticated;

grant delete, insert, references, select, trigger, truncate, update on variables to service_role;

